### ISSUE TITLE
Add "count" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/set#1]
Add a new `.count(predicate: T => boolean)` method that returns the number of items matching the given `predicate`

**Example**

```js
Set.of([1, 2, 3, 4, 5]).count(value => {
  return value > 3
})

// 2
```

**Comment by MatheusMuriel** [comment]
I can do it. You can assing to me?

**Comment by marcuspoehls** [comment]
@MatheusMuriel Hey Matheus, please go ahead and submit a pull request 👍
