### ISSUE TITLE
Add method: all

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/set#17]
Implement an `all` method that returns `true` if all items in the set match a given `predicate` function, otherwise false.

### Requirements
- please use the prepared [`method-all` branch (contains tests)](https://github.com/supercharge/set/compare/main...method-all)
- make sure the automated tests pass

**Comment by aniket-24** [comment]
Please assign me this issue under Hacktoberfest!

**Comment by crypto-cmd** [comment]
@marcuspoehls Hey,👋! Since hacktoberfest is over and this issue is not fixed am I allowed to do it?

**Comment by marcuspoehls** [comment]
@crypto-cmd Hey Orville, of course you are 😃 I'm happy if you're sending a pull request 😊
