### ISSUE TITLE
Add method: findLast

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/set#19]
Implement a `findLast` method that returns the last item in the set matching the given `predicate` function. Returns `undefined` if no item matching the predicate was found in the set.

### Requirements
- please use the prepared [`method-findLast` branch (contains tests)](https://github.com/supercharge/set/compare/main...method-findLast)
- make sure the automated tests pass

**Comment by crypto-cmd** [comment]
Hey @marcuspoehls . 
I would like to try to do this issue. May I?

**Comment by marcuspoehls** [comment]
@crypto-cmd Hey Orville, this issue is meant to be solved as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com). If you want, you can tackle this issue as part of the upcoming Hacktoberfest 😃

**Comment by marcuspoehls** [comment]
@crypto-cmd Hey Orville, this issue is meant to be solved as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com). If you want, you can tackle this issue as part of the upcoming Hacktoberfest 😃

**Comment by crypto-cmd** [comment]
@marcuspoehls Oh okay. Does that mean I should wait until October (Hacktoberfest begins)?

**Comment by marcuspoehls** [comment]
@crypto-cmd Yes, please wait until October :) I’m going ahead and assign this issue to you. You can already start the implementation if you want. Please just wait until October for the pull request 👍 

Waiting until October gives me some more time to prepare issues for anyone who wants to contribute. It also helps to to batch the reviews.

**Comment by crypto-cmd** [comment]
@marcuspoehls Great, thanks! 😁

**Comment by marcuspoehls** [comment]
@crypto-cmd 🤝  you’re welcome!

**Comment by aniket-24** [comment]
Please assign me this issue under Hacktoberfest!

**Comment by marcuspoehls** [comment]
@aniket-24 Hey, this issue is already assigned to another person.
