### ISSUE TITLE
Add "includes" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/set#2]
Add a new `.includes(value: T | predicate: T => boolean)` method that determines whether the set includes the given `value` or a value identified by the predicate function.

Returns `true` if the value is found in the collection or the predicate function returns an item from the collection. Returns `false` otherwise.

**Example**

```js
Set.of([1, 2, 3, 4, 5]).includes(2)
// true

Set.of([1, 2, 3, 4, 5]).includes(value => {
  return value > 3
})
// true

Set.of([1, 2, 3, 4, 5]).includes(value => {
  return value === 0
})
// false

```

**Comment by binkpitch** [comment]
Can i take this issue?

**Comment by marcuspoehls** [comment]
@binkpitch Hey, yeah sure.

**Comment by marcuspoehls** [comment]
@binkpitch please notice there's already pull request #5. You can also approach another issue: #4 or #1

**Comment by binkpitch** [comment]
@marcuspoehls Got it.

**Comment by binkpitch** [comment]
@marcuspoehls I notice that #4 and #1 has already been assigned but has been inactive. Can I take both issues?

**Comment by marcuspoehls** [comment]
@binkpitch Yeah sure. Both of the other two issues are inactive for 10 days. I appreciate if you want to submit pull requests for one or both 👍
