### ISSUE TITLE
Add method: findLastIndex

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/set#20]
Implement a `findLastIndex` method that returns the index of the last item in the set matching the given `predicate` function. Returns `-1` if no item matching the predicate was found in the set.

### Requirements
- please use the prepared [`method-findLastIndex` branch (contains tests)](https://github.com/supercharge/set/compare/main...method-findLastIndex)
- make sure the automated tests pass

**Comment by binkpitch** [comment]
Can I take this issue?

**Comment by marcuspoehls** [comment]
@binkpitch sure 👍
