### ISSUE TITLE
Add method: intersect

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/set#21]
Implement an `intersect` method that returns a set containing all items that are contained in all collections, the given set and and all candidate `sets`.

### Requirements
- please use the prepared [`method-intersect` branch (contains tests)](https://github.com/supercharge/set/compare/main...method-intersect)
- make sure the automated tests pass

**Comment by Sundava** [comment]
Hi, can I take this ?

**Comment by marcuspoehls** [comment]
@Sundava Hey Antoine, this issue is meant to be solved as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com). If you want, you can tackle this issue as part of the upcoming Hacktoberfest 😃 

It would be nice if you can wait until October before submitting a pull request :) I’m still going ahead and assign this issue to you now. You can already start the implementation if you want. Waiting until October gives me some more time to prepare issues for anyone who wants to contribute. It also helps to batch the code reviews for all submissions.

**Comment by Sundava** [comment]
Quick question about the test from the `method-intersect` branch here:
https://github.com/supercharge/set/blob/method-intersect/test/set.js#L518-L520

The test seems to expect the result of the intersection between `ids` and the *combinations* of the two sets `Set.from([2, 3])` and `Set.from([1, 4, 5, 6]`.
This doesn't seem to match "contained in the given set and all candidate `sets`" but is more like "contained in the given set and any of the candidate `sets`"

Which one is the desired behaviour ? I assume the former, in which case this specific test should expect an empty array.

**Comment by marcuspoehls** [comment]
@Sundava Good catch! Thank you for pointing this out! You’re right, the test is wrong and we’re expecting the intersection between all given sets. That means the expectation for your described case should be an empty array because there’s no overlap between all given sets 👍
