### ISSUE TITLE
Add "reduce" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/set#3]
Add a new `.reduce(operation, initialValue)` method executes a reducer function on each item of the set, resulting in a single output value.

The method signature may look like this (I’m writing this freestyle, you may need to refine it when working in the code 😄 )

```js
reduce<U>((operation: (previous: U, current: T, set: Set), initial: U): U`
```

**Example**

```js
Set.of([1, 2, 3, 4]).reduce((sum, value) => {
  return sum + value
}, 0)

// 10
```

**Comment by Kolkies** [comment]
I'm working on this!
