### ISSUE TITLE
Add "concat" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/set#4]
Add a new `.concat(...values)` method that appends the given values to the end of the set.

**Example**

```js
Set.of([1, 2, 3]).concat([4, 5]).toArray()
// [1, 2, 3, 4, 5]

Set.of([1, 2, 3]).concat(4, 5).toArray()
// [1, 2, 3, 4, 5]
```

**Comment by Rookie3109** [comment]
Hey! Could you assign it to me? I'd love to work on it for hacktoberfest!

**Comment by marcuspoehls** [comment]
Sure!
