### ISSUE TITLE
Add "last" method

### ISSUE THREAD

**Issue by marcuspoehls** [supercharge/set#9]
Add a new  `.last(predicate?: (value: T, set: SuperchargedSet)` method returns the last item in the set. If a `predicate` function is provided, return the last item found by `predicate`.

**Example**

```js
Set.of([1, 2, 3]).last()
// 3

Set.of([5, 4, 3, 2, 1]).last(value => {
  return value > 3
})
// 4
```

**Comment by rohitgeddam** [comment]
I would be happy to try this. Can you please assign me?

**Comment by marcuspoehls** [comment]
@rohitgeddam Hey, please go ahead and submit a pull request if you want to work on this feature.

As a note: there’s an existing pull request #12, but it’s not mergeable yet. You can still offer your solution if you want. I’m happy to assist you with the implementation or review any code!
